"""add category foreignkey

Revision ID: 36852cd37f20
Revises: 9a91d4f28720
Create Date: 2024-10-08 10:23:03.119401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36852cd37f20'
down_revision = '9a91d4f28720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
