"""add catetory relationship to product

Revision ID: 49de57fa82c3
Revises: 36852cd37f20
Create Date: 2024-10-08 11:36:50.789201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49de57fa82c3'
down_revision = '36852cd37f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_photo')
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product_category_id', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_product_category_id', 'category', ['category_id'], ['id'])

    op.create_table('_alembic_tmp_photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
